apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: casdoor
  namespace: argocd
  labels:
    app: casdoor
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/LeonhardtHUST/casdoor.git
    targetRevision: master
    path: k8s/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: casdoor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
